---
openapi: 3.0.2
info:
    version: 2.0.0
    title: Simpplr API Documentation
    description: ""
tags:
    - name: Alerts
      description: Everything about Alerts v2.0


servers:
     - url: https://platform.{env}.simpplr.xyz/{version}
       variables:
         env:
            default: dev
         version:
            default: v2
paths:

    # Alerts
    /alerts:
        $ref: "./paths/alerts/v2.0/create-search.yaml"
    /alerts/{alertId}:
        $ref: "./paths/alerts/v2.0/update-delete.yaml"
    
components:
    schemas:
        $ref: "./schemas/_index.yaml"
    responses:
        $ref: "./responses/_index.yaml"
    securitySchemes:
        apiAuthSecurity:
            type: "oauth2"
            description: "This API uses OAuth 2 with the implicit grant flow."
            flows:
                implicit:
                    authorizationUrl:  https://platform.test.simpplr.xyz/v1
                    scopes:
                        read: "read data"
                        write: "create/update data"
                        everything: "allow full access"
security:
    - apiAuthSecurity: []
