---
openapi: 3.0.2
info:
    version: 1.0.0
    title: Simpplr User API Documentation
    description: ""
x-proxy-enabled: true
tags:
    - name: Authorization
      description: Everything about Authorization
    - name: Alerts
      description: Everything about Alerts
    - name: Audience
      description: Everything about Audience
    - name: Content
      description: Everything about Content
    - name: Enterprise search
      description: Everything about Enterprise search
    - name: Files
      description: Everything about Files
    - name: Notifications
      description: Everything about Notifications
    - name: People
      description: Everything about People
    - name: Recognition
      description: Everything about Recognition
    - name: Sites
      description: Everything about Sites
    - name: Video
      description: Everything about Video

servers:
    - url: https://platform.{env}.simpplr.com/v1
      variables:
        env:
            default: app
paths:
    # Authorization
    /identity/oauth/token:
        $ref: "./paths/identity/token.yaml"

    # Notifications
    /notifications:
        $ref: "./paths/notifications/create-search.yaml"
    /notifications/{notificationId}:
        $ref: "./paths/notifications/delete-update.yaml"

    # Alerts
    /alerts:
        $ref: "./paths/alerts/create-search.yaml"
    /alerts/{alertId}:
        $ref: "./paths/alerts/update-delete.yaml"

    # Audience
    /identity/audience:
        $ref: "./paths/identity/create_audience.yaml"
    /identity/audience/{audienceId}:
        $ref: "./paths/identity/update_audience.yaml"

    # Audience v2
    /identity/audiences:
        $ref: "./paths/identity/audiences_v2.yaml"
    /identity/audiences/{audienceId}:
        $ref: "./paths/identity/audience_by_id_v2.yaml"
    /identity/audiences/{audienceId}/update:
        $ref: "./paths/identity/update_audience_v2.yaml"

    # People
    /identity/people:
        $ref: "./paths/identity/get_people_list.yaml"
    /identity/people/{peopleId}:
        $ref: "./paths/identity/update_people.yaml"

    # Video
    /video/tokens:
        $ref: "./paths/video/tokens.yaml"
    /video/entry/update:
        $ref: "./paths/video/update_status.yaml"
    /video/languages:
        $ref: "./paths/video/languages.yaml"
    /video/search:
        $ref: "./paths/video/search.yaml"

    # Sites
    /content/sites:
        $ref: "./paths/content/user/sites.yaml"
    /content/sites/{site_id}:
        $ref: "./paths/content/user/site_by_id.yaml"
    /content/sites/{site_id}/status:
        $ref: "./paths/content/user/site_status.yaml"
    /content/sites/{site_id}/membership/manage:
        $ref: "./paths/content/user/manage_site_membership.yaml"

    # Content
    /content/sites/content/list:
        $ref: "./paths/content/search_content.yaml"
    /content/sites/list:
        $ref: "./paths/content/search_sites.yaml"
    /content/sites/{site_id}/content/{content_id}:
        $ref: "./paths/content/get_content_by_id.yaml"
    /content/site-categories:
        $ref: "./paths/content/user/site_categories.yaml"
    /content/sites/{site_id}/content/{content_id}/status:
        $ref: "./paths/content/user/publish_unpublish_content.yaml"
    /content/site-categories/{siteCategoryId}:
        $ref: "./paths/content/user/site_category_by_id.yaml"
    /content/sites/{site_id}/page:
        $ref: "./paths/content/user/add_page.yaml"
    /content/sites/{site_id}/page-categories:
        $ref: "./paths/content/user/site_page_categories.yaml"
    /content/sites/{site_id}/page-categories/{category_id}:
        $ref: "./paths/content/user/site_page_category_by_id.yaml"

    # Files
    /content/static/signedurl/upload:
        $ref: "./paths/content/user/get_upload_signed_url.yaml"
    /content/files/list:
        $ref: "./paths/content/user/get_files.yaml"

    # Recognition Activity
    /recognition/activity:
        $ref: "./paths/recognition/get_activity.yaml"

     # Enterprise Search
    /enterprise-search/search:
        $ref: "./paths/search/top_search.yaml"
    /enterprise-search/autocomplete:
        $ref: "./paths/search/autocomplete_search.yaml"
    /enterprise-search/smartanswers:
        $ref: "./paths/search/smart_answers.yaml"

components:
    schemas:
        $ref: "./schemas/_index.yaml"
    responses:
        $ref: "./responses/_index.yaml"
    securitySchemes:
        apiAuthSecurity:
            type: "oauth2"
            description: "This API uses OAuth 2 with the implicit grant flow."
            flows:
                implicit:
                    authorizationUrl:  https://platform.test.simpplr.xyz/v1
                    scopes:
                        read: "read data"
                        write: "create/update data"
                        everything: "allow full access"
security:
    - apiAuthSecurity: []
