---
openapi: 3.0.2
info:
    version: 1.0.0
    title: Simpplr API Documentation
    description: ""
tags:
    - name: Notifications
      description: Everything about notifications
servers:
    - url: https://api.dev.simpplr.xyz/v1
paths:
    /notification/create:
        $ref: "./services/ec-zeus/docs/paths/notifications/create.yaml"
    /notification/list:
        $ref: "./services/ec-zeus/docs/paths/notifications/search.yaml"
    /notification/{notificationId}:
        $ref: "./services/ec-zeus/docs/paths/notifications/update.yaml"
components:
    schemas:
        $ref: "./services/ec-zeus/docs/schemas/_index.yaml"
    responses:
        $ref: "./services/ec-zeus/docs/responses/_index.yaml"
    securitySchemes:
        apiAuthSecurity:
            type: "oauth2"
            description: "This API uses OAuth 2 with the implicit grant flow."
            flows:
                implicit:
                    authorizationUrl: https://api.dev.simpplr.xyz/v1/identity/oauth/authorize
                    scopes:
                        read: "read data"
                        write: "create/update data"
                        everything: "allow full access"
security:
    - apiAuthSecurity: []
