microservicesName:
  slack-api-app:
    autoscalingMinReplicas: 2
    autoscalingMaxReplicas: 2

configMap:
  data:
    NODE_ENV: PROD
    PORT: '5000'
    ENV: PROD
    AWS_SM_API_VERSION: 2017-10-17
    AWS_SM_REGION: eu-west-1
    LOG_LEVEL: info
