#***********************************************************************************************************#
# Dev Deployment Variables #
#***********************************************************************************************************#
microservicesName:
  ec-odin-service:
    nodeSelector:
      label: graviton-daemon
    tolerations:
      - effect: NoSchedule
        key: taint
        operator: Equal
        value: graviton-daemon
    tolerationsEnabled: true
    nodeSelectorEnabled: true

#***********************************************************************************************************#
# ConfigMap Variables #
#***********************************************************************************************************#
configMap:
  data:
    NODE_ENV: UAT
    PORT: '5000'
    ENV: UAT
    DB_DIALECT: postgres
    AWS_SM_REGION: us-west-2
    AWS_SM_KMS_KEY_ID: f94c1031-a1b8-4ddf-adf4-7da5a8959b66
    LOG_LEVEL: info