#***********************************************************************************************************#
# Dev Deployment Variables #
#***********************************************************************************************************#
microservicesName:
  ec-odin-app:
    nodeSelector:
      label: graviton-daemon
    tolerations:
      - effect: NoSchedule
        key: taint
        operator: Equal
        value: graviton-daemon
    tolerationsEnabled: true
    nodeSelectorEnabled: true

#***********************************************************************************************************#
# ConfigMap Variables #
#***********************************************************************************************************#
configMap:
  data:
    NODE_ENV: UAT
    PORT: '5000'
    ENV: UAT
    DB_DIALECT: postgres
    AWS_SM_REGION: ap-southeast-2
    AWS_SM_KMS_KEY_ID: 272b60b3-5f25-4119-91c5-3585e4ac33fa
    LOG_LEVEL: info