name: Sync OpenAPI definition to ReadMe (PROD ZEUS)

# Run workflow for every push to the `release` branch
on:
  push:
    branches:
      - release

jobs:
  SyncToProd:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: 'https://platform.simpplr.com/'
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set Node.js version to 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

          # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: Validate and upload OpenAPI docs
        working-directory: ./services/ec-zeus
        run: |
          cd docs
          npx rdme@10 openapi upload ./ec-api-doc.yaml --key=${{ secrets.README_API_KEY }} --slug=simpplr-user-api-documentation
          npx rdme@10 openapi upload ./ec-api-doc-b2b.yaml --key=${{ secrets.README_API_KEY }} --slug=simpplr-b2b-api-documentation