name: Sync OpenAPI definition to ReadMe (PROD ZEUS)

# Run workflow for every push to the `release` branch
on:
  push:
    branches:
      - release

jobs:
  SyncToProd:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: 'https://platform.simpplr.com/'
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: Sync OpenAPI definition to ReadMe production
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v10
        with:
          working-directory: ./services/ec-zeus/docs
          rdme: openapi ec-api-doc.yaml --workingDirectory=./services/ec-zeus/docs --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID }}

      - name: Sync OpenAPI B2B definition to ReadMe production
        uses: readmeio/rdme@v10
        with:
          working-directory: ./services/ec-zeus/docs
          rdme: openapi upload ./services/ec-zeus/docs/ec-api-doc-b2b.yaml --key=${{ secrets.README_API_KEY }} --slug=simpplr-b2b-api-documentation.json
