name: Sync OpenAPI definition to ReadMe (DEV ZEUS)

# Run workflow for every push to the `develop` branch
on:
  push:
    branches:
      - develop

jobs:
  SyncToDev:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: 'https://hellosimpplr.readme.io/'
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      # Run GitHub Action to sync OpenAPI file at ./path-to-file.json
      - name: Sync OpenAPI definition to ReadMe Development
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          working-directory: ./services/ec-zeus/docs
          rdme: openapi ec-api-doc-dev.yaml --workingDirectory=./services/ec-zeus/docs --key=${{ secrets.DEV_README_API_KEY }} --id=${{ secrets.DEV_API_DEFINITION_ID }}

      - name: Sync v2.0 OpenAPI definition to ReadMe Development 
        # We recommend specifying a fixed version, i.e. @v8
        # Docs: https://docs.github.com/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
        uses: readmeio/rdme@v8
        with:
          working-directory: ./services/ec-zeus/docs
          rdme: openapi ec-api-doc-v2.0-dev.yaml --workingDirectory=./services/ec-zeus/docs --key=${{ secrets.DEV_README_API_KEY }} --id=${{ secrets.DEV_API_DEFINITION_V2_ID }} --version=2.0


      - name: Sync OpenAPI B2B definition to ReadMe Development
        uses: readmeio/rdme@v8
        with:
          working-directory: ./services/ec-zeus/docs
          rdme: openapi ec-api-doc-b2b-dev.yaml --workingDirectory=./services/ec-zeus/docs --key=${{ secrets.B2B_DEV_README_API_KEY }} --id=${{ secrets.B2B_DEV_API_DEFINITION_ID }}

