name: Microservice Deployment - Prod Environment
run-name: Deploying ${{ inputs.artifact }} to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        type: choice
        required: true
        options:
          - qa
          - uat
          - prod
          - prod-eu
          - devops-infra
      branch:
        description: 'Branch name'
        type: choice
        required: true
        options:
          - release
          - hotfix
      artifact:
        description: 'Artifact Version'
        type: string
        required: false
  schedule:
    - cron: '00 18 * * *'

jobs:
  deploy:
    name: Service Deployment
    uses: Simpplr/github-shared-library/.github/workflows/service-deploy.yaml@main
    with:
      BRANCH: "${{ inputs.branch }}"
      ENVIRONMENT: "${{ inputs.environment }}"
      ARTIFACT: "${{ inputs.artifact }}"
      TEAM_NAME: "integration"
    secrets: inherit
    if: github.event_name == 'workflow_dispatch'